using GoogleCloudPrintApi.Attributes;
using GoogleCloudPrintApi.Models.Job;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using GoogleCloudPrintApi.Infrastructures;

namespace GoogleCloudPrintApi.Models.Printer
{
    public class ControlRequest: IRequest
    {
        /// <summary>
        /// Unique job identification (generated by server). (required)
        /// </summary>
        [FormKey(isRequiredFor: VersionOption.All)]
        public string JobId { get; set; }

        /// <summary>
        /// Print Job State Diff, use this to update the state type (and cause if the type is ABORTED or STOPPED) and the number of printed pages. (required for GCP 2.0)
        /// </summary>
        [FormKey("semantic_state_diff", isRequiredFor: VersionOption.V2), V2DeterminationKey]
        public PrintJobStateDiff SemanticStateDiff { get; set; }

        /// <summary>
        /// Legacy job status.
        /// </summary>
        [FormKey, Obsolete("please use semantic_state_diff instead")]
        public LegacyJobStatus Status { get; set; }

        /// <summary>
        /// Error code string or integer (as returned by the printer or OS) if the status is ERROR.
        /// </summary>
        [FormKey, Obsolete("please use semantic_state_diff instead")]
        public string Code { get; set; }

        /// <summary>
        /// Error message string (as returned by the printer or OS) if the status is ERROR.
        /// </summary>
        [FormKey, Obsolete("please use semantic_state_diff instead")]
        public string Message { get; set; }
    }
}
