using GoogleCloudPrintApi.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GoogleCloudPrintApi.Models.Printer
{
    public class DeleteRequest
    {
        /// <summary>
        /// Unique printer identification (generated by Google Cloud Print). (required)
        /// </summary>
        [Required]
        public string PrinterId { get; set; }
    }
}
