using GoogleCloudPrintApi.Attributes;
using GoogleCloudPrintApi.Infrastructures;
using Newtonsoft.Json;

namespace GoogleCloudPrintApi.Models.Printer
{
    public class DeleteJobRequest : IRequest
    {
        /// <summary>
        /// Unique printer identification (generated by Google Cloud Print). (required)
        /// </summary>
        [JsonProperty("jobid"), Form(isRequiredFor: VersionOption.All)]
        public string JobId { get; set; }
    }
}
