using GoogleCloudPrintApi.Attributes;
using GoogleCloudPrintApi.Infrastructures;
using Newtonsoft.Json;

namespace GoogleCloudPrintApi.Models.Printer
{
    public class FetchRequest : IRequest
    {
        /// <summary>
        /// Unique printer identification (generated by Google Cloud Print). (required)
        /// </summary>
        [JsonProperty("printerid"), Form(isRequiredFor: VersionOption.All)]
        public string PrinterId { get; set; }
    }
}